{{- if .Values.storage.statements }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "tracker.fullname" . }}
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
data:
  statements.yaml: |
    {{ .Values.storage.statements | toYaml | indent 4 }}
{{- end }}
