{{- if and (not .Values.externalStorage.secretRef.name) (not .Values.externalStorage.configMapRef.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracker.fullname" . }}
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
stringData:
  STORAGE_DRIVER: {{ .Values.storage.driver | quote }}
  STORAGE_ADDRESS: {{ .Values.storage.address | quote }}
  STORAGE_READ_ONLY_ADDRESS: {{ .Values.storage.readOnlyAddress | quote }}
{{- end }}
