apiVersion: v1
kind: Service
metadata:
  name: {{ include "extractor.fullname" . }}
  labels:
    {{- include "extractor.labels" . | nindent 4 }}
spec:
  {{- if eq "Headless" .Values.service.type }}
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpclb
  selector:
    {{- include "extractor.selectorLabels" . | nindent 4 }}
