language: minimal
if: branch = master

before_install:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  - helm init --client-only

script:
  - bash generate.sh

deploy:
  provider: pages
  github_token: $GITHUB_RELEASE_TOKEN
  local_dir: dist
  target_branch: gh-pages
  verbose: true
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
