{{- if and (not .Values.externalStorage.secretRef.name) (not .Values.externalStorage.configMapRef.name) }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "tracker.fullname" . }}
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
data:
  STORAGE_DRIVER: {{ .Values.storage.driver | b64enc | quote }}
  STORAGE_ADDRESS: {{ .Values.storage.address | b64enc | quote }}
  STORAGE_READ_ONLY_ADDRESS: {{ default "" .Values.storage.readOnlyAddress | b64enc | quote }}
{{- end }}
