apiVersion: v1
entries:
  depscloud:
  - apiVersion: v2
    appVersion: latest
    created: "2020-04-28T20:18:46.388442299Z"
    dependencies:
    - condition: extractor.enabled
      name: extractor
      repository: file://../extractor
      version: 0.1.4
    - condition: gateway.enabled
      name: gateway
      repository: file://../gateway
      version: 0.1.4
    - condition: indexer.enabled
      name: indexer
      repository: file://../indexer
      version: 0.1.5
    - condition: tracker.enabled
      name: tracker
      repository: file://../tracker
      version: 0.1.5
    description: A Helm chart for Kubernetes
    digest: 649b6c0ca6f649f5e478860018cae54c786ab88bb3d1f76626e9fddc5be39dd4
    name: depscloud
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/depscloud-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: latest
    created: "2020-04-28T20:18:46.386796744Z"
    dependencies:
    - condition: extractor.enabled
      name: extractor
      repository: file://../extractor
      version: 0.1.3
    - condition: gateway.enabled
      name: gateway
      repository: file://../gateway
      version: 0.1.3
    - condition: indexer.enabled
      name: indexer
      repository: file://../indexer
      version: 0.1.4
    - condition: tracker.enabled
      name: tracker
      repository: file://../tracker
      version: 0.1.4
    description: A Helm chart for Kubernetes
    digest: 1188e595d8653b76476095dd5b3d059bab2f2e808d44d01fce53407b5b4b95c7
    name: depscloud
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/depscloud-0.1.0.tgz
    version: 0.1.0
  extractor:
  - apiVersion: v2
    appVersion: 0.2.7
    created: "2020-04-28T20:18:46.389942853Z"
    description: A Helm chart for running the deps-cloud extractor process
    digest: c15c1ef5aaa70693c94e6c97f6fcf9ad3b41c45e2584fb52d83f41e5caa1d9d2
    name: extractor
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/extractor-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.2.7
    created: "2020-04-28T20:18:46.389562537Z"
    description: A Helm chart for running the deps-cloud extractor process
    digest: 729daefb2c0baa42d8e47cf4857d7132574cf32de9afa5f2dac8576dad19874d
    name: extractor
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/extractor-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.2.6
    created: "2020-04-28T20:18:46.38919733Z"
    description: A Helm chart for running the deps-cloud extractor process
    digest: 1712222e42dc40971124493faa643ff651dd103b686e3e1fc2369d06fc4bc7e7
    name: extractor
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/extractor-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.2.4
    created: "2020-04-28T20:18:46.388837802Z"
    description: A Helm chart for running the deps-cloud extractor process
    digest: 7d0c4e690f3508c50adaef123557a809e04e06bccb725237d52b7369db3de2e8
    name: extractor
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/extractor-0.1.1.tgz
    version: 0.1.1
  gateway:
  - apiVersion: v2
    appVersion: 0.2.5
    created: "2020-04-28T20:18:46.391621814Z"
    description: A Helm chart for running the deps-cloud gateway process
    digest: 662eb9ff93e7981aeb288528adca0ec8ef6052e23aa998949d6aefc4dc210384
    name: gateway
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/gateway-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.2.5
    created: "2020-04-28T20:18:46.391203403Z"
    description: A Helm chart for running the deps-cloud gateway process
    digest: bf24bddbc9ba7187d00461e1bc72ad841fccaf3599c434e74cf798fbac453278
    name: gateway
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/gateway-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.2.2
    created: "2020-04-28T20:18:46.390787058Z"
    description: A Helm chart for running the deps-cloud gateway process
    digest: b8ebe038f736c1803dff9eeb70a3e850f730c787b06326b66fe194f2bb66d601
    name: gateway
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/gateway-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.2.2
    created: "2020-04-28T20:18:46.39034044Z"
    description: A Helm chart for running the deps-cloud gateway process
    digest: e569bc6cb792314e777eda630212fefa80bd9e52a21c67f5eb03c3114307167e
    name: gateway
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/gateway-0.1.1.tgz
    version: 0.1.1
  indexer:
  - apiVersion: v2
    appVersion: 0.2.4
    created: "2020-04-28T20:18:46.395219703Z"
    description: A Helm chart for running the deps-cloud indexer process
    digest: de9f6e4fc5feee7a11d84531841750adc54f05ba0c038a4b8b6aa6970c57e773
    name: indexer
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/indexer-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.2.4
    created: "2020-04-28T20:18:46.39419933Z"
    description: A Helm chart for running the deps-cloud indexer process
    digest: 9c378686c0954b283c5b950fc35e115d93789c1207da058996baaa45aa0970cf
    name: indexer
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/indexer-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.2.4
    created: "2020-04-28T20:18:46.392922969Z"
    description: A Helm chart for running the deps-cloud indexer process
    digest: 4a1243baba8b93131309c569624ca3a5bf0dd7c9957263c43ed5c5ca28b5c1a3
    name: indexer
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/indexer-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.2.3
    created: "2020-04-28T20:18:46.392464315Z"
    description: A Helm chart for running the deps-cloud indexer process
    digest: 998f74584324a3e16047b077ca447873de7c472f142dbb80c3e0614ec0a1c8ee
    name: indexer
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/indexer-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.2.3
    created: "2020-04-28T20:18:46.392025363Z"
    description: A Helm chart for running the deps-cloud indexer process
    digest: 1fd9d382261550f45d50a9e9ccbbb84d03b22e9f7814a738a5fa8f661af4f355
    name: indexer
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/indexer-0.1.1.tgz
    version: 0.1.1
  tracker:
  - apiVersion: v2
    appVersion: 0.2.4
    created: "2020-04-28T20:18:46.398424513Z"
    description: A Helm chart for running the deps-cloud tracker process
    digest: 9908b572cec91badb3a9f252219eb2d17aaffeaa1e79fa96d3e2a2b99afa8dba
    name: tracker
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/tracker-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.2.4
    created: "2020-04-28T20:18:46.397901785Z"
    description: A Helm chart for running the deps-cloud tracker process
    digest: 085ce4d4c48ed6831b9ae02ad4058c5b153459236cf00b0be8af105a01f79311
    name: tracker
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/tracker-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.2.4
    created: "2020-04-28T20:18:46.397395463Z"
    description: A Helm chart for running the deps-cloud tracker process
    digest: 8db88caa4da454dd5ed1dfe0be5ffec813f3a30b05d1efc10f8cfcda609f7848
    name: tracker
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/tracker-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.2.3
    created: "2020-04-28T20:18:46.396183977Z"
    description: A Helm chart for running the deps-cloud tracker process
    digest: 1135f537eba8be302e411c9eb09ada9f9a9a317674c24af86294d628d94cd19d
    name: tracker
    type: application
    urls:
    - https://deps-cloud.github.io/deploy/charts/tracker-0.1.2.tgz
    version: 0.1.2
generated: "2020-04-28T20:18:46.384460704Z"
