{{- if and (not .Values.externalConfig.configMapRef.name) (not .Values.externalConfig.secretRef.name) }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "indexer.fullname" . }}
  labels:
    {{- include "indexer.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.config | toYaml | b64enc }}
{{- end }}
