version: "3.7"

services:
  tracker:
    restart: always
    image: depscloud/tracker:${TRACKER_VERSION:-latest}
    hostname: tracker
    volumes:
      - ./certs:/etc/depscloud/certs
    command:
      - --tls-key=/etc/depscloud/certs/tracker.key
      - --tls-cert=/etc/depscloud/certs/tracker.crt
      - --tls-ca=/etc/depscloud/certs/ca.crt

  extractor:
    restart: always
    image: depscloud/extractor:${EXTRACTOR_VERSION:-latest}
    hostname: extractor
    volumes:
      - ./certs:/etc/depscloud/certs
    command:
      - --tls-key=/etc/depscloud/certs/extractor.key
      - --tls-cert=/etc/depscloud/certs/extractor.crt
      - --tls-ca=/etc/depscloud/certs/ca.crt
    
  indexer:
    restart: on-failure
    image: depscloud/indexer:${INDEXER_VERSION:-latest}
    hostname: indexer
    depends_on:
      - extractor
      - tracker
    volumes:
      - ./certs:/etc/depscloud/certs
      - ./config.yaml:/etc/indexer/config.yaml
    command:
      - --cron
      - --workers=1
      - --rds-config=/etc/indexer/config.yaml
      - --extractor-key=/etc/depscloud/certs/indexer.key
      - --extractor-cert=/etc/depscloud/certs/indexer.crt
      - --extractor-ca=/etc/depscloud/certs/ca.crt
      - --tracker-key=/etc/depscloud/certs/indexer.key
      - --tracker-cert=/etc/depscloud/certs/indexer.crt
      - --tracker-ca=/etc/depscloud/certs/ca.crt

  gateway:
    restart: always
    image: depscloud/gateway:${GATEWAY_VERSION:-latest}
    hostname: gateway
    depends_on:
      - extractor
      - tracker
    volumes:
      - ./certs:/etc/depscloud/certs
    command:
      - --tls-key=/etc/depscloud/certs/localhost.key
      - --tls-cert=/etc/depscloud/certs/localhost.crt
      - --tls-ca=/etc/depscloud/certs/ca.crt
      - --extractor-key=/etc/depscloud/certs/gateway.key
      - --extractor-cert=/etc/depscloud/certs/gateway.crt
      - --extractor-ca=/etc/depscloud/certs/ca.crt
      - --tracker-key=/etc/depscloud/certs/gateway.key
      - --tracker-cert=/etc/depscloud/certs/gateway.crt
      - --tracker-ca=/etc/depscloud/certs/ca.crt
    ports:
      - 8080:8080
